### ISSUE TITLE
Will it work on EE 6.x

### ISSUE THREAD

**Issue by alexhobday** [vector/VMG-Chosen-Member#28]
@lukewilkins Sorry to contact you this way. Just wondering if this plugin will work in EE 6.x. We use it extensively on our 2.x site which we are now finally upgrading to 6.x.

Thanks

**Comment by mrw** [comment]
Hi @alexhobday! Unfortunately we haven't tested it on EE 6, so can't say for certain. If you run into issues and are able to fix them, feel free to submit a pull request and we can take a look at merging it! But right now we don't have an anticipated timeline for being able to test it there.

**Comment by freddaw** [comment]
@alexhobday. I was wondering whether you tested VMG Chosen Member in EE6 yet, and if so were there any issues. OR, have you found an EE6 compatible alternative? I have an EE5+ site, where it is working, but am still hesitating to upgrade to EE6.

**Comment by haydentech** [comment]
We are attempting to use it on EE 6.4.14.  When I try to edit a channel, I get this:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'rspace.exp_member_groups' doesn't exist:
SELECT `mg`.`group_id`, `mg`.`group_title` FROM (`exp_member_groups` AS mg) GROUP BY `mg`.`group_id`, `mg`.`group_title`

ee/legacy/database/drivers/mysqli/mysqli_connection.php:114
Stack Trace: Please include when reporting this error

    #0 system\ee\legacy\database\drivers\mysqli\mysqli_driver.php(112): CI_DB_mysqli_connection->query()
    #1 system\ee\legacy\database\DB_driver.php(260): CI_DB_mysqli_driver->_execute()
    #2 system\ee\legacy\database\DB_driver.php(175): CI_DB_driver->simple_query()
    #3 system\ee\legacy\database\DB_active_rec.php(1083): CI_DB_driver->query()
    #4 system\user\addons\vmg_chosen_member\helper.php(390): CI_DB_active_record->get()
    #5 system\user\addons\vmg_chosen_member\ft.vmg_chosen_member.php(286): ChosenHelper->getMemberGroups()
    #6 system\user\addons\vmg_chosen_member\ft.vmg_chosen_member.php(377): Vmg_chosen_member_ft->display_settings()
    #7 system\ee\legacy\libraries\api\Api_channel_fields.php(381): Vmg_chosen_member_ft->grid_display_settings()
    #8 system\ee\legacy\libraries\Grid_parser.php(671): Api_channel_fields->apply()
    #9 system\ee\ExpressionEngine\Addons\grid\libraries\Grid_lib.php(1032): Grid_parser->call()
    #10 system\ee\ExpressionEngine\Addons\grid\ft.grid.php(532): Grid_lib->get_settings_form()
    #11 system\ee\ExpressionEngine\Addons\grid\ft.grid.php(567): Grid_ft->getSettingsVars()
    #12 system\ee\legacy\libraries\api\Api_channel_fields.php(381): Grid_ft->display_settings()
    #13 system\ee\ExpressionEngine\Model\Content\FieldFacade.php(314): Api_channel_fields->apply()
    #14 system\ee\ExpressionEngine\Model\Content\FieldModel.php(78): ExpressionEngine\Model\Content\FieldFacade->getSettingsForm()
    #15 system\ee\ExpressionEngine\Controller\Channels\Channels.php(349): ExpressionEngine\Model\Content\FieldModel->getSettingsForm()
    #16 system\ee\ExpressionEngine\Controller\Channels\Channels.php(169): ExpressionEngine\Controller\Channels\Channels->form()
    #17 [internal function]: ExpressionEngine\Controller\Channels\Channels->edit()
    #18 system\ee\ExpressionEngine\Core\Core.php(266): call_user_func_array()
    #19 system\ee\ExpressionEngine\Core\Core.php(122): ExpressionEngine\Core\Core->runController()
    #20 system\ee\ExpressionEngine\Boot\boot.php(161): ExpressionEngine\Core\Core->run()

**Comment by mrw** [comment]
Hi @haydentech! Unfortunately we're no longer supporting this add-on. If you fix this issue, feel free to submit a pull request and we can consider merging it! But right now we don't have an anticipated timeline for being able to test on or support EE6.
